### ISSUE TITLE
визуальные блоки

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#10]
**To Reproduce**

https://user-images.githubusercontent.com/108226177/214195927-d242d122-c7b2-41f9-a5e8-2e7540e6d0de.mp4

Быстро ставить блоки(например драг-клик) и они визуальные(кликаю пропадают) на видео я  вам показал

**Plugins**
Работает и без плагинов баг.

**Version**
[04:41:55 INFO]: This server is running Reaper version git-Reaper-1edc26b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by ruViolence** [comment]
В конфиге Paper поставь `incoming-packet-spam-threshold` в ноль.
