### ISSUE TITLE
Порталы

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#13]
Если кидать любую вещь в портал незера(вожмоно работает и в энде) то вещи пропадают и не появляются в другом измирение

**Comment by ghost** [comment]
пропадают так же мобы... исправьте пожалуйста <3

**Comment by ghost** [comment]
без него все хорошо https://github.com/ruViolence/Reaper/blob/ver/1.12.2/patches/server/0053-fix-entity-portal-dupe.patch

**Comment by ruViolence** [comment]
Спасибо за информацию. Исправлено в https://github.com/ruViolence/Reaper/commit/24d710260e22585d72f63aa7c895f80184da2059
