### ISSUE TITLE
визуальные открыты шалкера, сундуки

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#16]
версия ласт после фикса порталов

![Screenshot_1](https://user-images.githubusercontent.com/108226177/218262319-418cf257-6ace-4976-bfcd-86a4ecae8af6.png)
суть: кликаю нормал кликом(иногда драгкликаю и открываю и так пару раз и чаще такой баг) и оно вечно так открыто

**Comment by ghost** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/108226177/218329397-ab01cdd7-9308-4587-8af6-3f6e1a5cb4bc.png)

**Comment by ghost** [comment]
incoming-packet-spam-threshold: 0
вроде помогло, открою тикет если нет

**Comment by ruViolence** [comment]
Нет. Проблема не решена.

**Comment by ghost** [comment]
> Нет. Проблема не решена.

хорошо :c

**Comment by ruViolence** [comment]
Этот баг, похоже, по дефолту присутствует в 1.12.2. Добавил фичу чтобы избавиться от этого в https://github.com/ruViolence/Reaper/commit/3da078f2f6d92f93fb46b751c7470955282dda78. Её предварительно нужно будет включить в конфиге: `drop-use-packets-in-inventory`. Но с ней теоретически могут появиться и другие баги с какими-то плагинами.

**Comment by ghost** [comment]
> Этот баг, похоже, по дефолту присутствует в 1.12.2. Добавил фичу чтобы избавиться от этого в [3da078f](https://github.com/ruViolence/Reaper/commit/3da078f2f6d92f93fb46b751c7470955282dda78). Её предварительно нужно будет включить в конфиге: `drop-use-packets-in-inventory`. Но с ней теоретически могут появиться и другие баги с какими-то плагинами.

не знаю но на paper либо же dionysus(от которого ушел на ваш прекрасный форк) все было нормально, но спасибо, гляну!

**Comment by ruViolence** [comment]
Хмм, похоже ты прав. Так что, по сути, все исправлено было было еще тут https://github.com/ruViolence/Reaper/commit/65670a7bff497f0379bd225f7f94affbc7c07c41, однако, вечно открытые эндер сундуки это проблема всего 1.12.2. Фича с дропом пакетов поможет и это исправить.

**Comment by F3F5** [comment]
@ruViolence проблема осталась.
