### ISSUE TITLE
иногда игроки в мире после выхода несколько секунд(30s примерно)

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#17]
а кикает их за timeout после того как 30s или меньше пройдет. ихможно бить это не визуал
тестил без плагинов, баг такой же, вроде на диносусе баг тоже такой же  и на папере

**Comment by ghost** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/108226177/218262567-a351f3ab-bf2c-483c-9e30-44d95c28e732.png)
скинул тикет своему другу, че он думает по поводу этого:

**Comment by ghost** [comment]
у нас у обеех хостинги разные, вывод ядр

**Comment by ghost** [comment]
доп.инфо, чтоб проверить баг получше: с 1.12.2 клиента закрываешь игру полностью через крестик (прям на сервере) и ты все еще в игре

**Comment by ruViolence** [comment]
Если это присутствует на всех остальных ядрах, то проблема в хосте. В Reaper нет никаких серьезных изменений, которые могут вести к разрывам соединения.

**Comment by ghost** [comment]
> Если это присутствует на всех остальных ядрах, то проблема в хосте. В Reaper нет никаких серьезных изменений, которые могут вести к разрывам соединения.

я все же думаю что это баг, ведь если крестиком выйти из сервера то такой баг почти всегда. а хостинги у нас разные и такая же проблема. проверьте пожалуйста :c

**Comment by ghost** [comment]
повторяюсь, именно если крестиком выйти из сервера потом пишешь в консоль list либо же своим 2 аккаунтом наблюдаешь а игрок стоит секунд 10-30 так а потом только исчезает

**Comment by ruViolence** [comment]
У тебя Bungee/Velocity стоит? Если нет то накинь сверху, может поможет. Хостить один Paper это слишком архаично.

**Comment by ghost** [comment]
> У тебя Bungee/Velocity стоит? Если нет то накинь сверху, может поможет. Хостить один Paper это слишком архаично.

нет, но я был рад был бы если бы проверили на себе этот баг:)

не архаично потому что уже есть современные плагины

**Comment by ruViolence** [comment]
Ну так. Еще раз, если баг и на других ядрах есть, то что тут поделаешь? На моем сервере за банджой такого нет, на локалке тоже.

**Comment by ghost** [comment]
> Ну так. Еще раз, если баг и на других ядрах есть, то что тут поделаешь? На моем сервере за банджой такого нет, на локалке тоже.

я к тому что попробовать исправить, и сделать идеальное ядро)

**Comment by ghost** [comment]
> Ну так. Еще раз, если баг и на других ядрах есть, то что тут поделаешь? На моем сервере за банджой такого нет, на локалке тоже.

ладно, спасибо за ответ.

**Comment by ghost** [comment]
по 1 тесту могу скзаать с шансом 80% что виноват хостинг, на другом фришном проверял
