### ISSUE TITLE
Стойки не падают вниз

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#18]
![Screenshot_1](https://user-images.githubusercontent.com/108226177/218330065-d28d0de4-75b0-470b-be54-8078e615a6da.png)

**Comment by ghost** [comment]
если это оптимизация, то добавьте опцию чтобы они падали плз

**Comment by ruViolence** [comment]
Они прекрасно падают. У тебя либо `armor-stands-tick` выключен в конфиге paper, либо какой-то плагин вмешивается.

**Comment by ghost** [comment]
> Они прекрасно падают. У тебя либо `armor-stands-tick` выключен в конфиге paper, либо какой-то плагин вмешивается.

да, спасибо)
