### ISSUE TITLE
Пропадает энтити 

### ISSUE THREAD

**Issue by xKumorio** [ruViolence/Reaper#21]
https://github.com/ruViolence/Reaper/blob/ver/1.12.2/patches/server/0140-feat-configurable-portal-exit-chunks-generation.patch
Вызывает пропажу энтити при входе в портал если чанки в другом мире не были загружены

**Comment by ruViolence** [comment]
Провел тесты. Этот баг еще в Paper присутствует, так что патч тут не виноват. На выходе почему-то создается 1 сломанный портал и предмет вылетает куда-то вниз. По крайней мере это так, если портал спавнится над морем. В любом случае, надо будет разбираться.

**Comment by ghost** [comment]
@ruViolence кинул я туда корову  в портал где чанки не были прогружены(где нет воды) она разбилась об высоту, кинул предмет он полетал и упал

**Comment by ghost** [comment]
однако забавно, пофикси пожалуйста)

**Comment by ghost** [comment]
у меня тоже на этот счет догадок на баг мысли были, хотел протестировать
