### ISSUE TITLE
Плохая оптимизация с ядром 

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#25]
Сами тайминги: https://timings.aikar.co/dev/?id=5d79858bdd0e4442b2f4460425b2db29
Спарк: https://spark.lucko.me/xjHFwXZAOn
Суть в том что на других ядрах ситуация лучше вроде бы 

*я бы очень благодарен был бы если бы вы мне помогли* @ruViolence

**Comment by ghost** [comment]
наверное что то с этим W: https://github.com/Elecast2/EntityTrackerFixer, пожалуйста исправьте в ядре оптимизацию

**Comment by ghost** [comment]
ситуация при 6-8 онлайне на сегодня: https://timings.aikar.co/dev/?id=a6907a0fcaf4400ca59c5d2e92f689af @ruViolence

**Comment by ghost** [comment]
Тайминги с другим ядром: https://timings.aikar.co/dev/?id=59a2f9d0ce074f93b15d35a20eea9368 @ruViolence

**Comment by xKumorio** [comment]
Так на таймингах 20 тпс

**Comment by xKumorio** [comment]
\<html>
<body>


Max Memory | 1024MB
-- | --



</body>
</html>


Ты чё гонишь?

**Comment by ghost** [comment]
> <html>
> 
> Max Memory	1024MB
> Ты чё гонишь?

научись читать тайминги, в ядре проблема с чанками/ентити. в том же dionysus такого нет

**Comment by xKumorio** [comment]
> > Max Memory	1024MB
> > Ты чё гонишь?
> 
> научись читать тайминги, в ядре проблема с чанками/ентити. в том же dionysus такого нет

Может быть потому-что в тот момент чанки не грузили?

**Comment by ghost** [comment]
> > > Max Memory	1024MB
> > > Ты чё гонишь?
> > 
> > 
> > научись читать тайминги, в ядре проблема с чанками/ентити. в том же dionysus такого нет
> 
> Может быть потому-что в тот момент чанки не грузили?

чанки не грузили игроки, а ядро все равно вызывало лаги, с dionysus ситуаций таких нету

**Comment by ghost** [comment]
тики сами по себе на 1.12.2 лагают,и это баг. нужно бы его оптимизировать

**Comment by ghost** [comment]
проблема не актуальна @ImNotSoftik сменили хостинг с 5гб озу.

**Comment by ghost** [comment]
Проблема актуальна на новом хостинге но только с Entity
Хотя тпс 20 :)
https://timings.aikar.co/dev/?id=5b1d2e92d32a440382ea11ffad975ebd

**Comment by ghost** [comment]
проблему должен решить per-player-mob-spawn, если добавят..

**Comment by ruViolence** [comment]
У тебя на таймингах генерация чанков тпс положила

**Comment by ghost** [comment]
> У тебя на таймингах генерация чанков тпс положила

в данный момент грузят entity сильновато но на тпс не влияет, хостинг новый.
