### ISSUE TITLE
Ванильный баг в коде

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#26]
Суть: иногда когда ставишь лодку она пропадает и чтоб появилась нужно кликнуть по слоту. Я думаю все же это ванильный баг.

**Comment by ghost** [comment]
часто случается  если ставить лодку на лед. давольно популярнй баг

**Comment by F3F5** [comment]
Тайминги с другим ядром: https://timings.aikar.co/dev/?id=59a2f9d0ce074f93b15d35a20eea9368 @ruViolence

**Comment by F3F5** [comment]
Тайминги с другим ядром: https://timings.aikar.co/dev/?id=59a2f9d0ce074f93b15d35a20eea9368 @ruViolence
