### ISSUE TITLE
дракон не агрится на игрока с дефолт настрами ядра и без плагинов

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#29]
название все говорит,  а версия ласт в /ver пишет :) а еще в других ядер бага такого нет, проверенно

**Comment by ghost** [comment]
а если быть точнее вечно летает

**Comment by ghost** [comment]
entity-tracker-y:true сработал и бага нет

**Comment by F3F5** [comment]
тпс стал скакать до 17-19 после включения entity-tracker

**Comment by ghost** [comment]
если это баг, переоткройте тикет
