### ISSUE TITLE
Grim + 1.8 механика

### ISSUE THREAD

**Issue by rejomy** [ruViolence/Reaper#34]
OldCombatMechanics всё норм, а у вас если включить механику 1.8 и viaversion, viarewind, viabackwards, и зайти с 1.8.8, начинается ужас, в инвентаре предметы не перемещаются нормально, еда очень странно кушается.

- Кстати, я просил запретить 2-ую руку, вы отказали, но разве качать доп. плагин тупо на ее отклбчение не затратнее в плане производительности?

**Comment by ghost** [comment]
up
проверял на его сервере , баг есть

**Comment by ghost** [comment]
но частично это баг грима, с олд комбатом +- так же но лучше в разы

**Comment by rejomy** [comment]
@ruViolence будет фикс этого?

**Comment by ruViolence** [comment]
Будет. Но пока нет времени на это.

**Comment by ruViolence** [comment]
Пробуй обновиться на последний дев билд рипера и выключить в конфиге `reduce-inventory-updates`. Возможно, поможет.

**Comment by rejomy** [comment]
> 

Не знаю, поставил последний билд, даже без выключения всё хорошо.
