### ISSUE TITLE
Timings

### ISSUE THREAD

**Issue by xKumorio** [ruViolence/Reaper#36]
Тайминги вроде как вырезаны, однако они по прежнему нагружают сервер
https://spark.lucko.me/qyIF3Tr4sE

**Comment by ruViolence** [comment]
А где нагружают-то?
![pic](https://user-images.githubusercontent.com/78062896/227993897-df5df278-ab9a-4092-b31f-fa579a9e8937.png)

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/108226177/227995271-d78ef248-d4e6-493c-9523-0561f9701b6b.png)



ты мне лучше скажи как эту грозу или эти молнии замедлить, они по кд..
