### ISSUE TITLE
use-faster-eigencraft-redstone (оптимизация редстоуна)

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#41]
можно сделать бекпорт с новой версии https://github.com/PaperMC/Paper/blob/master/patches/server/0466-Eigencraft-redstone-implementation.patch

**Comment by ruViolence** [comment]
Уже сейчас можно откопать и поставить PandaWire. Он тоже неплох 🤔

**Comment by ghost** [comment]
> Уже сейчас можно откопать и поставить PandaWire. Он тоже неплох 🤔

увы, я откопал под 1.12, он баганный и ошибки мог кидать(тестилось на чистом сервере с paper)

Free download of latest stable version: http://files.md-5.net/pandawire/PandaWire-1.15.2.jar
 я на http://files.md-5.net/pandawire/PandaWire-1.12.jar менял, 1.12.2 не находило. 
через ядро куда лучше будет

**Comment by ruViolence** [comment]
У меня вроде как раз 1.12 и стоит. Нормально работает. Если хочешь, может портировать сам и запилить PR. А то я смысла не вижу для себя, меня все устраивает.

**Comment by ghost** [comment]
> У меня вроде как раз 1.12 и стоит. Нормально работает. Если хочешь, может портировать сам и запилить PR. А то я смысла не вижу для себя, меня все устраивает.

я читал что на java 17 pandawire баганный
