### ISSUE TITLE
Citizens

### ISSUE THREAD

**Issue by BestMark** [ruViolence/Reaper#42]
Ядро не работает с Citizens, NPC не отображатся.

**Comment by ruViolence** [comment]
Ты используешь ядро из релиза? Там есть такой баг. Используй дев билд

**Comment by BestMark** [comment]
> Ты используешь ядро из релиза? Там есть такой баг. Используй дев билд

Использую как раз дев билд, скачивал отсюда: https://nightly.link/ruViolence/Reaper/workflows/dev-build/ver%2F1.12.2/Reaper-JDK8.zip. Ещё заметил, что если отойти далеко от НПС и перезайти на сервер, некоторых из них будет видно, когда подойдешь к ним.

**Comment by ruViolence** [comment]
Хмм. Я использую версию 2.0.30 и там все норм. Не тестил новые релизы

**Comment by BestMark** [comment]
> Хмм. Я использую версию 2.0.30 и там все норм. Не тестил новые релизы

И правда, с этим билдом (https://ci.citizensnpcs.co/job/Citizens2/2888/) всё хорошо, НПС видны. А с последним их уже не видно. Придётся использовать немножко устаревший билд Citizens.

**Comment by BestMark** [comment]
Также при заходе игроков Citizens выдаёт такую ошибку только с Reaper: https://pastebin.com/AgVsmivr

**Comment by BestMark** [comment]
Подскажите, пожалуйста, какой билд вы используете у себя на сервере? Попробую его поставить.

**Comment by ruViolence** [comment]
Citizens-2.0.30-b2665

**Comment by ruViolence** [comment]
Этот баг с новым Citizens есть и на Paper. Так что, проблема, похоже, в устрелости 1.12.2 😆
