### ISSUE TITLE
EntityTracker tick loop (java.lang.IllegalArgumentException: x not finite)

### ISSUE THREAD

**Issue by BestMark** [ruViolence/Reaper#45]
Во время работы сервера он периодически вылетает со следующей ошибкой: https://pastebin.com/C5MUzQ8A
Мой конфиг reaper.yml: https://pastebin.com/TmNvGzL5
Я предполагаю, что это связано с настройкой `entity-tracker-check-y: true`. Я так и не понял, за что отвечает эта опция, но поставил её на true по рекомендации F3F5.

**Comment by ruViolence** [comment]
Не. Какой-то плагин в `PlayerVelocityEvent` ставит кривую velocity. Проблема не в ядре.

**Comment by BestMark** [comment]
> Не. Какой-то плагин в `PlayerVelocityEvent` ставит кривую velocity. Проблема не в ядре.

У меня однозначно нет плагинов, которые используют метод PlayerVelocityEvent#setVelocity. Проверил все.

**Comment by BestMark** [comment]
Кроме того, один из моих плагинов стал вызывать тот же краш (java.lang.IllegalArgumentException: x not finite):
`    private void pushAway(final Player player, final Location pushFrom) {
        player.setVelocity(pushFrom.toVector().subtract(player.getLocation().toVector()).normalize().multiply(-1).multiply(1.2));
    }`

**Comment by BestMark** [comment]
> Не. Какой-то плагин в `PlayerVelocityEvent` ставит кривую velocity. Проблема не в ядре.

`Caused by: java.lang.IllegalArgumentException: x not finite
    at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:115) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
    at org.bukkit.util.Vector.checkFinite(Vector.java:624) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
    at org.bukkit.craftbukkit.v1_12_R1.entity.CraftEntity.setVelocity(CraftEntity.java:249) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
    at ru.bestmark.ForsShield.ForsShield.pushAway(ForsShield.java:62) ~[?:?]
    at ru.bestmark.ForsShield.ForsShield.onPlayerMove(ForsShield.java:46) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor177.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Reaper-"08ebad8"]
    ... 15 more`

**Comment by BestMark** [comment]
https://github.com/ruViolence/Reaper/blob/ver/1.12.2/patches/api/0008-fix-Bukkit-API.patch
Там написано, что это фиксит некоторые "плохие" плагины. Я использую самый простой код. Или этот краш вызван чем-то другим?

**Comment by BestMark** [comment]
![image](https://github.com/ruViolence/Reaper/assets/18399104/b4a7b4a1-e79b-483e-96b4-95f9dbef7a10)
https://github.com/ruViolence/Reaper/blob/ver/1.12.2/patches/server/0050-fix-NaN-pos-on-entity-data-save.patch
Возможно, сюда следует добавить ещё и такую проверку?

**Comment by ruViolence** [comment]
Сделал какой-то недофикс. Попробуй последний билд.

**Comment by BestMark** [comment]
> Сделал какой-то недофикс. Попробуй последний билд.

Спасибо огромное за фикс. Я сейчас удалил ViaRewind и ViaBackwards, заменил их на ProtocolSupport, и вроде бы всё нормализовалось, краша больше нет уже 2 дня. Подожду ещё несколько дней. Если краша больше не будет, напишу сюда, если будет - поставлю фикс и скажу, помог ли.

**Comment by BestMark** [comment]
Нашли способ повторить этого краш. Игроку нужно заюзать AntiKnockback (Velocity) чит, и когда сервер применит setVelocity() для него, то будет краш. Анти-чит Matrix помогает решить эту проблему, он сразу же кикает таких игроков.
![image](https://github.com/ruViolence/Reaper/assets/18399104/a5b40cf2-5bcc-458c-8ad2-96e6e22877d5)

**Comment by BestMark** [comment]
Краш (https://pastebin.com/C5MUzQ8A) повторился, поэтому я установил последний Reaper с фиксом. Посмотрим, поможет ли.

**Comment by BestMark** [comment]
Сервер все-ещё зависает. Как оказалось, причина зависания в чём-то другом, если посмотреть по дампу главного потока (Server thread). Бесконечный velocity - следствие того, что сервер зависает.
https://pastebin.com/qFHk4MZ0

**Comment by BestMark** [comment]
В плагине ForsPads нет ничего подозрительного, там всё просто:
`player.velocity = player.velocity.clone().setY(y)`

**Comment by BestMark** [comment]
![image](https://github.com/ruViolence/Reaper/assets/18399104/f22ed724-e2ef-45c2-b857-e11b39cc6ec9)

**Comment by ghost** [comment]
> Краш (https://pastebin.com/C5MUzQ8A) повторился, поэтому я установил последний Reaper с фиксом. Посмотрим, поможет ли.

хз, а без плагинов как?
у меня такого никогда не было

**Comment by ghost** [comment]
ForsPads виноват из-за строки   player.velocity = player.velocity.clone().setY(y) ?

**Comment by BestMark** [comment]
> ForsPads виноват из-за строки player.velocity = player.velocity.clone().setY(y) ?

Нет, он не виноват, там всё стандартно (y от 1.5 до 2, берётся из конфига при загрузке плагина), к тому же он не устанавливает x и z.
![image](https://github.com/ruViolence/Reaper/assets/18399104/4e393bcd-bef4-43d9-a049-9fc5736b2938)

**Comment by BestMark** [comment]
Я временно отключил этот плагин, но почти уверен, что сервер крашнется снова.

**Comment by ghost** [comment]
> Я временно отключил этот плагин, но почти уверен, что сервер крашнется снова.

и как

**Comment by ruViolence** [comment]
Проблема явно в плагинах, потому что у меня такой проблемы не возникает. Еще попробуй уменьшить силу velocity в ForsPads чтобы было не более 4-х, а то у тебя сервер ругается:
![img](https://github.com/ruViolence/Reaper/assets/78062896/23548422-dca3-417b-8f67-8f596acd671d)

**Comment by ghost** [comment]
> Проблема явно в плагинах, потому что у меня такой проблемы не возникает. Еще попробуй уменьшить силу velocity в ForsPads чтобы было не более 4-х, а то у тебя сервер ругается: ![img](https://user-images.githubusercontent.com/78062896/247904731-23548422-dca3-417b-8f67-8f596acd671d.png)
[ruViolence](https://github.com/ruViolence/Reaper/commits?author=ruViolence) [Suppress setVelocity crash](https://github.com/ruViolence/Reaper/commit/e362d32e71e21d5b4b8d0bb52c46ea6cb60de5bc) в чем смысл тогда, можно удалить патч

**Comment by BestMark** [comment]
Решил проблему. Она возникала из-за плагина на "щит", который отталкивал игроков в радиусе 3 блоков, и, чем ближе игрок, тем выше velocity, с которым отталкивает.
Когда кто-то включал этот щит и gamemode spectator, а потом вселялся в другого игрока с помощью наблюдателя, дистанция между ними была равна 0, и другого игрока отталкивало на бесконечность.
Фикс из ядра теперь можно убрать, он не нужен. Был виноват плагин, как и предполагалось.
