### ISSUE TITLE
краш сервера без эксплоитфиксера

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#47]
https://github.com/AntiCope/meteor-crash-addon/blob/master/src/main/java/widecat/meteorcrashaddon/modules/ErrorCrash.java
сам модуль
![image](https://github.com/ruViolence/Reaper/assets/137526883/891b5730-bfb7-4887-a727-350c397e7d48)

**Comment by ghost** [comment]
вызывает ошибки и крашит сервер без плагинов тоже

**Comment by ruViolence** [comment]
Проверяй

**Comment by ghost** [comment]
спасибо, больше не нужен эксплоитфиксер
