### ISSUE TITLE
Го получше оптимизацию? тайминги и 51 онлайна

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#48]
![image](https://github.com/ruViolence/Reaper/assets/137526883/05038383-e4e2-41d4-897b-7fbd1e711ece)
 https://spark.lucko.me/7xIz1Ao6cX

**Comment by ruViolence** [comment]
Не понял в чем проблема. Что на скрине, что в таймингах ТПС 20.

**Comment by ghost** [comment]
> Не понял в чем проблема. Что на скрине, что в таймингах ТПС 20.

судя по таймингам нагурзки есть net.minecraft.server.v1_12_R1.DedicatedServer.updateTimeLightAndEntities()50.76

**Comment by ruViolence** [comment]
Ничего не обычного. Если тебя это так тревожит, купи хост что-ли помощнее или урежь мобов, прорисовку. А так, думаю, где-то 70 игроков потянет твой сервер без лагов. При любом раскладе будет нарузка на сервер. Это ядро не задумывалось как ультра асинхрон в каждой строчке кода чтобы тянуть миллион игроков на одном сервере.

Да и как ты, возможно, заметил, последнее время мало каких-то изменений в ядре. Для меня отпала необходимость сидеть на 1.12, поэтому скоро заархивирую репо и полностью забью на это ядро.
