### ISSUE TITLE
Добавить в 1.8 механику запрет, при нажатии F, отменять перенос предмета во 2-ую руку.

### ISSUE THREAD

**Issue by rejomy** [ruViolence/Reaper#5]
Это нужно, чтобы игроки с 1.8 не имели странных вопросов, по типу, у него нет чар яблок, почему он регенится?

**Comment by ruViolence** [comment]
Привет. Я не хочу нагружать ядро тем, что можно сделать с помощью плагинов. То что тебе нужно может сделать плагин [OldCombatMechanics](https://www.spigotmc.org/resources/19510/). Выключи в конфиге всё лишнее и оставь отключение `offhand`.

**Comment by rejomy** [comment]
Так вы добавили пвп 1.8, а не хотите нагружать этим? Добавьте пожалуйста, я буду нагружать куда больше использую аддон к этому, чем если в кфг будет такая функция.
Ну будьте вы человеком а, я и так сегодня училкой посрался, не портите мне день пожалуйста!!!

> Привет. Я не хочу нагружать ядро тем, что можно сделать с помощью плагинов. То что тебе нужно может сделать плагин [OldCombatMechanics](https://www.spigotmc.org/resources/19510/). Выключи в конфиге всё лишнее и оставь отключение `offhand`.

**Comment by rejomy** [comment]
@ruViolence

**Comment by ruViolence** [comment]
@Regomy В том и дело, что это можно исправить с помощью плагинов. Незачем этому функционалу находиться в ядре сервера. Пвп 1.8 было добавлено потому что OldCombatMechanics как раз-таки неправильно делает свои расчёты урона, knockback'а и т.д. Поэтому проще напрямую внутри ядра расчитывать всё как в 1.8, чем расчитывать сначала под 1.12 а потом как-то пытаться это всё модифицировать. В любом случае, если тебе не нравится, можешь сделать форк и сам пропатчить ядро под свой вкус. Заодно посмотришь насколько сложно или легко это будет сделать.
