### ISSUE TITLE
проблема с jline

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#52]
просьба отключить jline
была проблема с флагами аикара( (консоль багалась)

**Comment by ruViolence** [comment]
А какая проблема-то? Зачем эти флаги ставить вообще тогда?

**Comment by ghost** [comment]
> А какая проблема-то? Зачем эти флаги ставить вообще тогда?

проблема в том что консоль через строку отображается с флагами aikar
но чтобы пофиксить можно добавить флаг но тогда цвет консоли пропадает
можно убрать вообще этот лищний jline и проблем не будет. новые версии уже давно отказались
