### ISSUE TITLE
А ГДЕ ЖЕ МОИ ПУЗЫРЬКИ!!!??

### ISSUE THREAD

**Issue by rejomy** [ruViolence/Reaper#7]
Баг: умераешь, если спавнешься в воде, то при респе нету пузырьков воздуха, сразу тебя дамагает.
Зач это фикс? Ну да, это же лишняя нагрузка ваще пздц, ну так проблемно, если респавнится без ресов, да еще и урон получить, голод быстрее тратится, и стартовать сложнее.

**Comment by ruViolence** [comment]
Исправлено в 1edc26b2c7ed4eb105efa996efa6c66554ff0b70
