### ISSUE TITLE
залагивание сервера порталом

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#8]
**Describe the bug**
если я захожу в портал ада далеко где нибудь где не прогружены чанки в обычно мире то сервер зависает на секунды 5.
проверял я на ядре спигот без плагинов с новым миром, ситуация та же
не могли ли вы оптимизировать данную проблему?
у меня так же ошибка в консоли: https://pastebin.com/bE1XgEBX

Reaper
**Version**
Show the output of /version here.
[16:56:10 INFO]: This server is running Reaper version git-Reaper-1edc26b (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by ghost** [comment]
если не сложно попробуйте... это для меня критикал issues из всех
 и на первом месте он https://github.com/ruViolence/Reaper/issues/17 тоже

**Comment by ruViolence** [comment]
Выведи тайминги через `/timings paste` и глянь. Возможно, у тебя процессор не успевает генерировать чанки.

**Comment by ghost** [comment]
> Выведи тайминги через `/timings paste` и глянь. Возможно, у тебя процессор не успевает генерировать чанки.

прям щас этим займусь.

**Comment by ghost** [comment]
> Выведи тайминги через `/timings paste` и глянь. Возможно, у тебя процессор не успевает генерировать чанки.

https://timings.aikar.co/dev/?id=bf274915d7e84d3e8bb236de6f249722

**Comment by ghost** [comment]
@ruViolence вот получше тайминги: https://timings.aikar.co/dev/?id=824d7a69d83841389c9b01707a7d589d and https://spark.lucko.me/a78zjB1o14

**Comment by ruViolence** [comment]
Spark как-то ты криво сделал, там нагрузки нет. Ну а обычные тайминги показывают что у тебя слишком долго чанки генерируются. Еще почему-то `entityRemoval` огромный, походу потому что в чанках много энтитей.

**Comment by ghost** [comment]
> Spark как-то ты криво сделал, там нагрузки нет. Ну а обычные тайминги показывают что у тебя слишком долго чанки генерируются. Еще почему-то `entityRemoval` огромный, походу потому что в чанках много энтитей.

в этом и проблема 'слишком долго' а насчет entity: 

  monsters: 20
  animals: 8
  water-animals: 3
  ambient: 1


а что делать?

**Comment by ghost** [comment]
удалось сделать хорошие тайминги  https://timings.aikar.co/dev/?id=1db8a9694d8d4b62bd1cb23a9e1f204d

а со спарком сложнее https://spark.lucko.me/OSzHv6JY2D

и видео я показываю подробное: https://streamable.com/pnodes

**Comment by ghost** [comment]
@ruViolence

**Comment by ruViolence** [comment]
Пропиши это перед заходом в портал `/spark profiler start --only-ticks-over 50` так нормальный репорт должен получиться.

**Comment by ghost** [comment]
> /spark profiler start --only-ticks-over 50

https://spark.lucko.me/QCR4gaen7T

**Comment by ghost** [comment]
а что с лагами делать? если тепатся просто на корды то не лагает ;c

**Comment by ruViolence** [comment]
Исправлено в https://github.com/ruViolence/Reaper/commit/559060403bb7eeea25c889abb1723ef485a27ba2

**Comment by ghost** [comment]
> Исправлено в [5590604](https://github.com/ruViolence/Reaper/commit/559060403bb7eeea25c889abb1723ef485a27ba2)

по дефолту фикс не включен да?

**Comment by ghost** [comment]
скоро проверю, если вы исправили я буду в шоцке

**Comment by ruViolence** [comment]
По дефолту опция выключена, что увеличит производительность.

**Comment by F3F5** [comment]
> Owner

проблема исправлена на 88%, после выхода тпс подлагивает только в течении секунд 5 но не замораживает сервер

**Comment by ghost** [comment]
проблема исправлена на 88%, после выхода тпс подлагивает только в течении секунд 5 но не замораживает сервер

@ruViolence

**Comment by ghost** [comment]
но теперь телепортироватся хоть можно и сервер не так сильно после тп лагает
