### ISSUE TITLE
API Reaper сломано

### ISSUE THREAD

**Issue by ghost** [ruViolence/Reaper#9]
Версию я кидал и прочее на 1 issues ниже, так вот..
Если например включить UltimateAntiBot вас просто не впустит, ядро ломает API плагинов
Еще один пример Citizencs, орет ошибками.
Вам нужно исправить API чтобы многие плагины работали которые ранее не работали/
У вас API изменен bukkit'a
*тот же paper,dionysus это все поддерживает

**Comment by rejomy** [comment]
Плюс

**Comment by ruViolence** [comment]
Скинь логи или версии плагинов, чтобы было с чем работать. А то так не понятно. Я сам пока ни с какими проблемами не сталкивался. Новейшие версии Citizens я тоже пробовал и работают исправно.

**Comment by ghost** [comment]
> Скинь логи или версии плагинов, чтобы было с чем работать. А то так не понятно. Я сам пока ни с какими проблемами не сталкивался. Новейшие версии Citizens я тоже пробовал и работают исправно.
например - https://www.spigotmc.org/resources/ultimate-antibot-%E2%9A%A1-firewall-anti-vpn-%E2%9A%A1-bungeecord-spigot-600-servers.93439/

**Comment by ghost** [comment]
Плагин вас заблокирует и подумает что вы бот, но если поставить другое ядро то все хорошо, так же разработчик сообщил что у вас проблемы с api и с выходом 4.0.6 исправит он вашу совместимость, но факт остается что оно ломает api

**Comment by ghost** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/108226177/213841653-4cc3331c-f9fa-4e63-be6f-77c270dd1636.png)

**Comment by ruViolence** [comment]
Я так понимаю UltimateAntiBot надо тестить на сервере с публичным айпишником. У меня нет такой возможности. Потому что на локалке нормально впустило.

**Comment by ghost** [comment]
возможно, создайте просто на любом free хостинг, например тот же(г***) рашанодес

**Comment by ghost** [comment]
вероятно не актуально, в старых версиях такой баг, в новых вроде нету
